# Generated by Django 2.2.6 on 2019-10-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0002_gan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gan',
            name='image',
        ),
    ]
