# Generated by Django 2.2.6 on 2019-10-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0003_remove_gan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gan',
            name='seconddescription',
        ),
    ]
