# Generated by Django 2.2.6 on 2019-10-27 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0004_remove_gan_seconddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='gan',
            name='seconddescription',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
