# Generated by Django 2.2.6 on 2019-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0005_gan_seconddescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gan',
            old_name='subtitle',
            new_name='sub1title',
        ),
        migrations.AddField(
            model_name='gan',
            name='sub2title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
