# Generated by Django 2.2.6 on 2019-10-27 19:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0006_auto_20191027_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub1title', models.CharField(max_length=100)),
                ('sub2title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('seconddescription', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'van',
                'verbose_name_plural': 'van',
                'db_table': 'van',
            },
        ),
    ]
