# Generated by Django 2.2.6 on 2019-10-27 19:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0007_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='sub3title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='sub4title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='thirddescription',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
