# Generated by Django 2.2.6 on 2019-10-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0008_auto_20191027_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms',
            name='sub2title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
