# Generated by Django 2.2.6 on 2019-10-28 05:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0009_cms_sub2title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub1title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('sub2title', models.CharField(max_length=100)),
                ('seconddescription', ckeditor.fields.RichTextField()),
                ('sub3title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('sub4title', models.CharField(max_length=100)),
                ('thirddescription', ckeditor.fields.RichTextField()),
                ('overview1', models.TextField()),
                ('sub5title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'cat',
                'verbose_name_plural': 'cat',
                'db_table': 'cat',
            },
        ),
    ]
