# Generated by Django 2.2.6 on 2019-10-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0010_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
