# Generated by Django 2.2.6 on 2019-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0011_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='description',
        ),
        migrations.AddField(
            model_name='cat',
            name='overview2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='overview3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='overview4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
