# Generated by Django 2.2.6 on 2019-10-28 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0012_auto_20191028_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('sub1title', models.CharField(max_length=100)),
                ('overview1', models.TextField()),
                ('overview2', models.TextField()),
                ('overview3', models.TextField()),
                ('sub2title', models.CharField(max_length=100)),
                ('sub3title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('sub4title', models.CharField(max_length=100)),
                ('overview4', models.TextField()),
                ('description2', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'home',
                'db_table': 'home',
            },
        ),
    ]
