# Generated by Django 2.2.6 on 2019-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0014_auto_20191028_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='hom',
            name='clientimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hom',
            name='courcetitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hom',
            name='nametitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
