# Generated by Django 2.2.6 on 2019-10-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0016_auto_20191028_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hom',
            old_name='overview1',
            new_name='classroomtraining',
        ),
        migrations.RenameField(
            model_name='hom',
            old_name='overview2',
            new_name='corporatetraining',
        ),
        migrations.RenameField(
            model_name='hom',
            old_name='overview3',
            new_name='onlinetraining',
        ),
    ]
