# Generated by Django 2.2.6 on 2019-10-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0017_auto_20191029_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hom',
            old_name='sub2title',
            new_name='popular',
        ),
        migrations.RenameField(
            model_name='hom',
            old_name='sub3title',
            new_name='trending',
        ),
    ]
