# Generated by Django 2.2.6 on 2019-10-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0018_auto_20191029_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hom',
            old_name='nametitle',
            new_name='customername',
        ),
    ]
