# Generated by Django 2.2.6 on 2019-10-29 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0020_auto_20191029_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hom',
            name='description2',
        ),
        migrations.AlterField(
            model_name='hom',
            name='stories',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
