# Generated by Django 2.2.6 on 2019-10-30 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0021_auto_20191029_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'contacted',
                'verbose_name_plural': 'contacted',
                'db_table': 'contacted',
            },
        ),
        migrations.AddField(
            model_name='hom',
            name='overview1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
