# Generated by Django 2.2.6 on 2019-11-02 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0022_auto_20191030_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('meritstep', ckeditor.fields.RichTextField()),
                ('contactus', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footer',
                'db_table': 'footer',
            },
        ),
        migrations.DeleteModel(
            name='Contacted',
        ),
    ]
