# Generated by Django 2.2.6 on 2019-11-02 05:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0023_auto_20191102_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'fot',
                'verbose_name_plural': 'fot',
                'db_table': 'fot',
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
