# Generated by Django 2.2.6 on 2019-11-02 06:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0024_auto_20191102_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'cos',
                'verbose_name_plural': 'cos',
                'db_table': 'cos',
            },
        ),
    ]
