# Generated by Django 2.2.6 on 2019-11-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0025_cos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffingimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'staffingimages',
                'verbose_name_plural': 'staffingimages',
                'db_table': 'staffingimages',
            },
        ),
    ]
