# Generated by Django 2.2.6 on 2019-11-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0026_staffingimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='seconddescription',
        ),
        migrations.RemoveField(
            model_name='van',
            name='sub2title',
        ),
    ]
