# Generated by Django 2.2.6 on 2019-11-02 14:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0028_instructor2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'instructor3',
                'verbose_name_plural': 'instructor3',
                'db_table': 'instructor3',
            },
        ),
        migrations.RemoveField(
            model_name='van',
            name='sub4title',
        ),
        migrations.RemoveField(
            model_name='van',
            name='thirddescription',
        ),
    ]
