# Generated by Django 2.2.6 on 2019-11-02 14:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0029_auto_20191102_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'corporate1',
                'verbose_name_plural': 'corporate1',
                'db_table': 'corporate1',
            },
        ),
        migrations.CreateModel(
            name='Corporate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'corporate2',
                'verbose_name_plural': 'corporate2',
                'db_table': 'corporate2',
            },
        ),
        migrations.RemoveField(
            model_name='cat',
            name='overview1',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='seconddescription',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sub2title',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sub5title',
        ),
    ]
