# Generated by Django 2.2.6 on 2019-11-02 17:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0031_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('liveprojects', models.CharField(max_length=100)),
                ('trainingoptions', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('title4', models.CharField(max_length=100)),
                ('description2', ckeditor.fields.RichTextField()),
                ('title5', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'coursedetail',
                'verbose_name_plural': 'coursedetail',
                'db_table': 'coursedetail',
            },
        ),
    ]
