# Generated by Django 2.2.6 on 2019-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0032_coursedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='title6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
