# Generated by Django 2.2.6 on 2019-11-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0033_coursedetail_title6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetail2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('coursefee', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'coursedetail2',
                'verbose_name_plural': 'coursedetail2',
                'db_table': 'coursedetail2',
            },
        ),
    ]
