# Generated by Django 2.2.6 on 2019-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0034_coursedetail2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail2',
            old_name='coursefee',
            new_name='particulars1',
        ),
        migrations.RemoveField(
            model_name='coursedetail2',
            name='image',
        ),
        migrations.AddField(
            model_name='coursedetail2',
            name='particulars2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail2',
            name='particulars3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail2',
            name='particulars4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail2',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
