# Generated by Django 2.2.6 on 2019-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0037_auto_20191103_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'courseimages',
                'verbose_name_plural': 'courseimages',
                'db_table': 'courseimages',
            },
        ),
    ]
