# Generated by Django 2.2.6 on 2019-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0038_courseimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursecol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'coursecol',
                'verbose_name_plural': 'coursecol',
                'db_table': 'coursecol',
            },
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='title8',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
