# Generated by Django 2.2.6 on 2019-11-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0039_auto_20191103_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecol',
            old_name='duration',
            new_name='overview',
        ),
    ]
