# Generated by Django 2.2.6 on 2019-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0040_auto_20191103_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='cus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
