# Generated by Django 2.2.6 on 2019-11-04 12:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0042_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fot',
            old_name='title',
            new_name='lefttitle',
        ),
        migrations.AddField(
            model_name='fot',
            name='description2',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fot',
            name='righttitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
