# Generated by Django 2.2.6 on 2019-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0043_auto_20191104_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'header',
                'db_table': 'header',
            },
        ),
        migrations.RemoveField(
            model_name='cat',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cms',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='van',
            name='title',
        ),
    ]
