# Generated by Django 2.2.6 on 2019-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0044_auto_20191104_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hom2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'hom2',
                'verbose_name_plural': 'hom2',
                'db_table': 'hom2',
            },
        ),
        migrations.RemoveField(
            model_name='hom',
            name='clientimage',
        ),
    ]
