# Generated by Django 2.2.6 on 2019-11-05 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0046_auto_20191104_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('published_by', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'blogers',
                'verbose_name_plural': 'blogers',
                'db_table': 'blogers',
            },
        ),
    ]
