# Generated by Django 2.2.6 on 2019-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0047_blogers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
