# Generated by Django 2.2.6 on 2019-11-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0048_blogers_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogers',
            new_name='Blog1',
        ),
        migrations.AlterModelOptions(
            name='blog1',
            options={'verbose_name': 'blog1', 'verbose_name_plural': 'blog1'},
        ),
        migrations.AlterModelTable(
            name='blog1',
            table='blog1',
        ),
    ]
