# Generated by Django 2.2.6 on 2019-11-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0051_get'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Get',
        ),
    ]
