# Generated by Django 2.2.6 on 2019-11-06 09:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0052_delete_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'touch',
                'verbose_name_plural': 'touch',
                'db_table': 'touch',
            },
        ),
    ]
