# Generated by Django 2.2.6 on 2019-11-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0054_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'modal',
                'verbose_name_plural': 'modal',
                'db_table': 'modal',
            },
        ),
    ]
