# Generated by Django 2.2.6 on 2019-11-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0055_modal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modal',
            options={'verbose_name': 'live_demo', 'verbose_name_plural': 'live_demo'},
        ),
        migrations.AddField(
            model_name='modal',
            name='course',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
