# Generated by Django 2.2.6 on 2019-11-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0056_auto_20191108_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homecontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'live_demo',
                'verbose_name_plural': 'live_demo',
                'db_table': 'homecontact',
            },
        ),
    ]
