# Generated by Django 2.2.6 on 2019-11-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0057_homecontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontact',
            options={'verbose_name': 'homecontact', 'verbose_name_plural': 'homecontact'},
        ),
        migrations.AddField(
            model_name='homecontact',
            name='mode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
