# Generated by Django 2.2.6 on 2019-11-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0058_auto_20191108_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog1',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blog'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Corporate Training', 'verbose_name_plural': 'Corporate Training'},
        ),
        migrations.AlterModelOptions(
            name='clientimages',
            options={'verbose_name': 'Home Client Images', 'verbose_name_plural': 'Home Client Images'},
        ),
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name': 'IT Staffing', 'verbose_name_plural': 'IT Staffing'},
        ),
        migrations.AlterModelOptions(
            name='contact1',
            options={'verbose_name': 'Contacted Form', 'verbose_name_plural': 'Contacted Form'},
        ),
        migrations.AlterModelOptions(
            name='corporate1',
            options={'verbose_name': 'Corporate_description', 'verbose_name_plural': 'Corporate_description'},
        ),
        migrations.AlterModelOptions(
            name='corporate2',
            options={'verbose_name': 'Clients Feedback', 'verbose_name_plural': 'Clients Feedback'},
        ),
        migrations.AlterModelOptions(
            name='cos',
            options={'verbose_name': 'Course-about', 'verbose_name_plural': 'Course-about'},
        ),
        migrations.AlterModelOptions(
            name='coursecol',
            options={'verbose_name': "Faq's", 'verbose_name_plural': "Faq's"},
        ),
        migrations.AlterModelOptions(
            name='coursedetail2',
            options={'verbose_name': 'MODES OF TRAINING', 'verbose_name_plural': 'MODES OF TRAINING'},
        ),
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name': 'Trusted By Companies Worldwide_images', 'verbose_name_plural': 'Trusted By Companies Worldwide_images'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer Success Stories', 'verbose_name_plural': 'Customer Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='fot',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='gan',
            options={'verbose_name': 'gan', 'verbose_name_plural': 'Support and Contactus'},
        ),
        migrations.AlterModelOptions(
            name='hom',
            options={'verbose_name': 'Home Page CMS', 'verbose_name_plural': 'Home Page CMS'},
        ),
        migrations.AlterModelOptions(
            name='homecontact',
            options={'verbose_name': 'Contacted from Home page', 'verbose_name_plural': 'Contacted from Home page'},
        ),
        migrations.AlterModelOptions(
            name='instructor2',
            options={'verbose_name': 'Become an Instructor - Items', 'verbose_name_plural': 'Become an Instructor - Items'},
        ),
        migrations.AlterModelOptions(
            name='instructor3',
            options={'verbose_name': 'Become an Instructor - OUR INSTRUCTORS', 'verbose_name_plural': 'Become an Instructor - OUR INSTRUCTORS'},
        ),
        migrations.AlterModelOptions(
            name='modal',
            options={'verbose_name': 'live_demo Form', 'verbose_name_plural': 'live_demo Form'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request a Free Demo Form', 'verbose_name_plural': 'Request a Free Demo Form'},
        ),
        migrations.AlterModelOptions(
            name='staffingimages',
            options={'verbose_name': 'Client staffingimages', 'verbose_name_plural': 'Client staffingimages'},
        ),
        migrations.AlterModelOptions(
            name='touch',
            options={'verbose_name': 'Get in touch with us Form', 'verbose_name_plural': 'Get in touch with us Form'},
        ),
        migrations.AlterModelOptions(
            name='van',
            options={'verbose_name': 'Become an Instructor', 'verbose_name_plural': 'Become an Instructor'},
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
    ]
