# Generated by Django 2.2.6 on 2019-11-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0059_auto_20191112_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_events',
            options={'verbose_name': 'Course Details - Events', 'verbose_name_plural': 'Course Details - Events'},
        ),
        migrations.AlterModelOptions(
            name='coursecol',
            options={'verbose_name': "Course Details - Faq's", 'verbose_name_plural': "Course Details - Faq's"},
        ),
        migrations.AlterModelOptions(
            name='coursedetail2',
            options={'verbose_name': 'Course Details - MODES OF TRAINING', 'verbose_name_plural': 'Course Details - MODES OF TRAINING'},
        ),
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name': 'Course Details - Trusted By Companies Worldwide_images', 'verbose_name_plural': 'Course Details - Trusted By Companies Worldwide_images'},
        ),
        migrations.AddField(
            model_name='course_events',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecol',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail2',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseimages',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='Courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meritapp.Courses'),
            preserve_default=False,
        ),
    ]
